name: Generate Snake Game

on:
  schedule: # Execute every 12 hours
    - cron: "* */12 * * *"
  workflow_dispatch:

jobs:
  build:
    name: Jobs to update data
    runs-on: ubuntu-latest
    steps:
      # Snake Animation
      - uses: Platane/snk@master  # Use the original action from Platane
        id: snake-gif
        with:
          github_user_name: trn64x  # Your GitHub username
          svg_out_path: dist/github-contribution-grid-snake2.svg
          snake_color: 'blue'

      # Deploy the generated snake to GitHub Pages
      - uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
